# Generated by Django 4.2.8 on 2024-01-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_sharing", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
    ]
