# Generated by Django 4.2.8 on 2024-01-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_sharing", "0003_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
